ETH-3740:
  api:
    market_ticker: KXBTCD-25OCT2117-T110999.99
  market_maker:
    trade_side: "yes"
    max_position: 10
    order_expiration: 1800
    gamma: 0.4
    k: 2.0
    sigma: 0.04
    T: 3600
    min_spread: 0.01
    position_limit_buffer: 0.2
    inventory_skew_factor: 0.005
  dt: 2.0