ETH-3740:
  api:
    market_ticker: KXBTCD-25OCT2117-T110999.99
  market_maker:
    trade_side: "yes"
    max_position: 10
    order_expiration: 1800
    gamma: 0.4
    k: 2.0
    sigma: 0.04
    T: 3600  # Fallback if expiry_time not set
    min_spread: 0.01
    position_limit_buffer: 0.2
    inventory_skew_factor: 0.005

    # Market expiration time (UTC) - Format: "YYYY-MM-DD HH:MM:SS"
    # Example: "2025-10-25 17:00:00" for a market closing at 5 PM UTC
    expiry_time: null  # Set to null to use T instead, or specify: "2025-10-25 21:17:00"

    # Dynamic timing configuration - adjusts strategy as expiration approaches
    dynamic_timing:
      enabled: true  # Set to false to disable dynamic timing features

      # Strategy phases (in minutes before expiry)
      # The bot will use the phase with the highest min_time_to_expiry that's less than current time remaining
      phases:
        # Normal trading phase (>60 minutes to expiry)
        normal:
          min_time_to_expiry: 60
          gamma_multiplier: 1.0        # Standard risk aversion
          spread_multiplier: 1.0        # Standard spreads
          order_size_multiplier: 1.0    # Full order sizes
          dt_override: null             # Use default dt

        # Wind-down phase (15-60 minutes to expiry)
        wind_down:
          min_time_to_expiry: 15
          gamma_multiplier: 1.5         # More conservative
          spread_multiplier: 1.3        # Wider spreads to reduce fills
          order_size_multiplier: 0.7    # Smaller orders
          dt_override: null

        # Aggressive unwind phase (5-15 minutes to expiry)
        aggressive_unwind:
          min_time_to_expiry: 5
          gamma_multiplier: 2.5         # Very conservative
          spread_multiplier: 2.0        # Much wider spreads
          order_size_multiplier: 0.4    # Much smaller orders
          dt_override: 1.0              # Update every second
          inventory_target_ratio: 0.5   # Try to reduce inventory to 50%

        # Emergency exit phase (<5 minutes to expiry)
        emergency_exit:
          min_time_to_expiry: 0
          gamma_multiplier: 5.0         # Extremely conservative
          spread_multiplier: 1.2        # Tighter spreads for better fills
          order_size_multiplier: 0.3    # Very small orders
          dt_override: 0.5              # Update twice per second
          inventory_target_ratio: 0.0   # Try to exit all positions

  dt: 2.0